default_stages: [commit, push]
default_language_version:
  python: python3.8
repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    - id: black
      args: [
        --line-length=100,
        --target-version=py38,
      ]
      exclude: ^(venv/|docs/)
      types: ['python']

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    - id: trailing-whitespace
    - id: check-docstring-first
    - id: check-yaml
    - id: debug-statements
    - id: name-tests-test
    - id: requirements-txt-fixer
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
      args: [
        --max-line-length=100,
        --target-version=py38,
      ]
      exclude: ^(venv/|docs/)
      types: ['python']
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
    - id: mypy
      additional_dependencies: [types-all]