apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitfast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitfast
  template:
    metadata:
      labels:
        app: bitfast
    spec:
      containers:
        - name: bitfast
          image: ewave112/bitfast-image:dev
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000
