name: build

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8]
        # python-version: [3.7, 3.8, 3.9]

    steps:
      # Checkout the latest code from the repo
      - name: Checkout repo
        uses: actions/checkout@v2
        # Setup which version of Python to use
      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
        # Display the Python version being used
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Set Env variables
        run: |
          touch .env
          echo "COINBASE_API_KEY=${{secrets.COINBASE_API_KEY}}" >> .env
          echo "COINBASE_SECRET_KEY=${{secrets.COINBASE_SECRET_KEY}}" >> .env
          echo "FAUNA_SECRET_KEY=${{secrets.FAUNA_SECRET_KEY}}" >> .env
          echo "ENV=${{secrets.ENV}}" >> .env
          echo "AWS_SECRET_KEY=${{secrets.AWS_SECRET_KEY}}" >> .env
          echo "AWS_ID=${{secrets.AWS_ID}}" >> .env
          echo "REDIS_HOST=${{secrets.REDIS_HOST}}" >> .env
          echo "REDIS_PORT=${{secrets.REDIS_PORT}}" >> .env
          echo "REDIS_PASSWORD=${{secrets.REDIS_PASSWORD}}" >> .env
          echo "REDIS_USERNAME=${{secrets.REDIS_USERNAME}}" >> .env
          cat .env
      - name: Install coverage and pytest
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        # Run the tests. I'm using pytest and coverage and the file is in the tests directory.
      - name: Run tests
        run: coverage run -m pytest
      - name: Get Code Coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
